#!/bin/sh

ARG="-d"

case "$1" in
    start)
        echo "Starting aesdsocket"
        start-stop-daemon -S -n aesdsocket -a /usr/bin/aesdsocket -- ${ARG}
        ;;
    stop)
        echo "Stopping aesdsocket"
        start-stop-daemon -K --signal -n aesdsocket 
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0

